version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel notice
    volumes:
      - redis_data:/data
#  es01:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
#    container_name: els
#    environment:
#      - node.name=es01
#      - discovery.type=single-node
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - els_data:/usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
volumes:
  redis_data:
    driver: local
#  els_data:
#    driver: local